language: python

python: 3.6

script: coverage run test.py

install: pip install -r requirements.txt

after_success: 
  - bash <(curl -s https://codecov.io/bash)
  - sphinx-build -nWT -b dummy . _build/html